# Mem Configuration Example

database:
  path: mem.duckdb

capture:
  frame:
    interval_seconds: 5
    jpeg_quality: 85
    enable_deduplication: false
    similarity_threshold: 95.0
  audio:
    chunk_duration_seconds: 300
    sample_rate: 16000

whisper:
  model: base
  language: auto
  fallback_language: en
  device: cpu

files:
  filename_format: YYYY-MM-DD_HH-MM-SS
  filename_regex: ^(\d{4})-(\d{2})-(\d{2})_(\d{2})-(\d{2})-(\d{2})$

api:
  host: 0.0.0.0
  port: 8000
  max_upload_size: 5368709120  # 5GB
  default_time_range_days: 1

logging:
  level: INFO
  debug_level: DEBUG
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"